### ISSUE TITLE
External json interface to the DOB

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#142]
Create an external json interface for most of the DOB features. Like subscribing too entities, send messages and requests, and register a handler.

Reported by: joelottosson

Original SourceForge Ticket `#143`: [safir/tickets/143](https://sourceforge.net/p/safir/tickets/143)

**Comment by joelottosson** [comment]
This feature was implemented in safir_websocket.

**Comment by joelottosson** [comment]
This feature was implemented in safir_websocket.
