### ISSUE TITLE
Consider introducing a Distribution Channel-like concept in Stewart

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#143]
The new distribution concept has ignored the need for Distribution Channels, to keep things simple. It makes things a lot more difficult with Ghosts and persistence etc.

But we need to think about whether this is needed in the future.

Reported by: DonOregano

Original SourceForge Ticket `#144`: [safir/tickets/144](https://sourceforge.net/p/safir/tickets/144)

**Comment by DonOregano** [comment]
Closing this for now. This is not needed at all right now. Reopen if it becomes something we should start thinking about.
