### ISSUE TITLE
Consider introducing Priority concept in Stewart

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#144]
In the current dose_com implementation there is a priority concept. However, these priorities are only considered on the network level. For proper prioritization the consideration of priorities has to propagate all the way up to the application and in/out queues.

Is this needed?

Reported by: DonOregano

Original SourceForge Ticket `#145`: [safir/tickets/145](https://sourceforge.net/p/safir/tickets/145)

**Comment by DonOregano** [comment]
Reopen if it becomes a wanted feature.
