### ISSUE TITLE
Improve handling of deleted injectable entities

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#173]
From the old Trac ticket:

> **Best possible archtecture regarding where to save timestamps for deleted entities**
> 
> In order to perform a correct merge for entities of type 'Injectable' the timestamps for deleted entities have to be saved "forever".
> 
> Today the solution is that IEX saves the deleted timestamps in a database and checks received entities towards this database before injecting them in the Dob. This means that the merge functionality is devided between two components (IEX and the Dob). Can we figure out a better design?

Reported by: DonOregano

Original SourceForge Ticket `#174`: [safir/tickets/174](https://sourceforge.net/p/safir/tickets/174)

**Comment by DonOregano** [comment]
This design seems to be set in stone now. Reopen if needed.
