### ISSUE TITLE
Write a script that cleans up OS primitives (e.g. boost interprocess files)

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#176]
Might be useful for clearing up other os primitives as well.

Reported by: DonOregano

Original SourceForge Ticket `#177`: [safir/tickets/177](https://sourceforge.net/p/safir/tickets/177)

**Comment by DonOregano** [comment]
Reopen if we ever get around to doing this. Does not really appear to be a problem rn.
