### ISSUE TITLE
Add function to work out what kind of request it was in Req/Resp proxies

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#178]
It might be useful to have functions in the request and response proxies for working out what type of request it was. E.g. Is it an Update or Create request?

Might also be useful in the Injected-proxy.

Reported by: DonOregano

Original SourceForge Ticket `#179`: [safir/tickets/179](https://sourceforge.net/p/safir/tickets/179)

**Comment by DonOregano** [comment]
Reopen if anyone wants this.
