### ISSUE TITLE
Investigate/Correct handling of Entity owner not in distribution channel

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#180]
From old Trac ticket:
> What happens if an entity owner/message sender resides in a node that does not belong to the corresponding distribution channel?
> Describe the behaviour. Change it if it is bad. 

Is there a similar situation in Stewart that needs to be handled?

Reported by: DonOregano

Original SourceForge Ticket `#181`: [safir/tickets/181](https://sourceforge.net/p/safir/tickets/181)

**Comment by DonOregano** [comment]
With the current features of Safir SDK Core 6.0/6.1 there is no such problem.
