### ISSUE TITLE
Add property subscriptions

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#182]
Adding code to subscribe for all classes implementing a property is not trivial. Adding the functionality to Dose would mean that the code only needed to be written once. 

Reported by: DonOregano

Original SourceForge Ticket `#183`: [safir/tickets/183](https://sourceforge.net/p/safir/tickets/183)

**Comment by DonOregano** [comment]
Reopen if we want to do this.
