### ISSUE TITLE
Make split classes easier to handle

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#186]
From old ticket:

> Split classes, eg Transient and Static parts of Tracks, are cumbersome to handle. The Static part is considered the main part and is the only part an application is supposed to subscribe for.
> It is much easier to handle Tracks if the Transient part exists when the Static part arrives. But since these parts are sent on different distribution channels, there is no guarantee that this will happen. No mattar of the order the owner creates the objects.
> 
> A proposal for handling this is to add a SetObjectArray method. The main part is at index 0 and the other parts at other indecies. Consistency could be guaranteed by piggybacking all objects on the main object transmission.

Reported by: DonOregano

Original SourceForge Ticket `#187`: [safir/tickets/187](https://sourceforge.net/p/safir/tickets/187)

**Comment by DonOregano** [comment]
We don't currently have distribution channels or unacked entities (see #225). So this is a bit obsolete. Reopen if needed.
