### ISSUE TITLE
Implement "hierarchic updates" in foreach

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#190]
This is an old Trac ticket, that had very little information in it. I've tried to explain it as far as I can remember it.

Hierarchic updates are not implemented in foreach.

Example:
Say we have two entity types A, with one member (x) and B, derived from A, adding one member (y). We have two instances, A1 and B1 of types A and B respectively.
It should be possible to use foreach to send an UpdateRequest of type A to both A1 and B1, that will update the x-member in both instances.

This does not appear to be implemented in foreach.

Reported by: DonOregano

Original SourceForge Ticket `#191`: [safir/tickets/191](https://sourceforge.net/p/safir/tickets/191)

**Comment by DonOregano** [comment]
Noone has complained about this. Reopen if needed.
