### ISSUE TITLE
Rewrite/restructure chapter 1 and 2 of Users Guide

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#191]
A better introduction to Core and Dob is needed.
Chapter 1.1 contains a *lot* of ackronyms...

Reported by: DonOregano

Original SourceForge Ticket `#192`: [safir/tickets/192](https://sourceforge.net/p/safir/tickets/192)

**Comment by DonOregano** [comment]
Oh, well, made some slight improvements for 6.1
