### ISSUE TITLE
Add more SI-types to type system

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#193]
Radiation units, such as Gy, Becquerel and Sievert. Exactly which units should be added needs to be checked with Saab.

Reported by: DonOregano

Original SourceForge Ticket `#194`: [safir/tickets/194](https://sourceforge.net/p/safir/tickets/194)

**Comment by DonOregano** [comment]
Any news on this?

**Comment by DonOregano** [comment]
Meh, noone seems to particularly want this... Reopen if it is needed.
