### ISSUE TITLE
Dob not optimized for frequent create/delete of entities

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#201]
References to deleted entity states is kept by the Dob until all subribers on the local node has got the OnDeletedCallback. In a multinod system dose_main subscribes to entities for sending to remote nodes which means that dose_main will also kepp a reference until the state is sent to all remote nodes.  

In a system where one or more applications create/delete new entity instances with a high frequency there is a risk that the subscibers (including dose_main) do not keep up with the create/delete rate resulting in a full shared memory.

We must decide if this design is acceptable for Stewart or if we should try to figure out how to mitigate this problem.  

Reported by: anderswiden

Original SourceForge Ticket `#202`: [safir/tickets/202](https://sourceforge.net/p/safir/tickets/202)

**Comment by DonOregano** [comment]
This is outside the scope of 6.1, so I'm removing this from the 6.1 milestone.

**Comment by DonOregano** [comment]
This will get solved by #445, so marking this as a duplicate.
