### ISSUE TITLE
Serialize objects directly to shared memory

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#210]
Currently dots objects are first serialized to local memory and then that is copied into shared memory, e.g. when sending a message.

Instead the object could be serialized directly into shared memory, potentially saving a bunch of time.

There used to be a lot of TODOs in the code about this, but they were removed in commit 
44838d914011acc79edd3706e45835d073c019c8.

Reported by: DonOregano

Original SourceForge Ticket `#211`: [safir/tickets/211](https://sourceforge.net/p/safir/tickets/211)

**Comment by DonOregano** [comment]
This can be reopened if we are likely to do this.
