### ISSUE TITLE
Propagate string representations of HandlerIds between apps and nodes

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#211]
Once upon a time the idea was that the string representations of the hashed types would be lazily propagated, so that an application could actually get a useful string instead of just a bunch of numbers when looking at handlers etc. This is meant as a debugging feature.

There are a whole bunch of placeholder routines for this in all the languages, e.g. PreviousEntityProxy::GetOwnerWithStringRepresentation() etc. These currently just return the numbers as a string, instead of trying to find out the real string.

Are we ever going to implement this feature? It is a "nice" thing to have when debugging, but since the propagation is lazy it must never be used for business logic. It seems like quite a lot of work...
This is really something that we need our customers to tell us if it is something that saves them significant amounts of time during debugging. Otherwise it seems unlikely to be worth implementing.

Reported by: DonOregano

Original SourceForge Ticket `#212`: [safir/tickets/212](https://sourceforge.net/p/safir/tickets/212)

**Comment by DonOregano** [comment]
Closing ticket since it seems unlikely to ever be worth implementing. Reopen if needed.
