### ISSUE TITLE
Generate warnings when Olib is used (deprecated) 

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#219]
Reported by: DonOregano

Original SourceForge Ticket `#220`: [safir/tickets/220](https://sourceforge.net/p/safir/tickets/220)

**Comment by DonOregano** [comment]
Olib will not be available if the SAFIR_NO_DEPRECATED preprocessor symbol is defined. But there is currently no deprecation warnings on Olib.

**Comment by DonOregano** [comment]
Remove olib from SAFIR_SDK_CORE_LIBRARIES and add a separate variable for Olib.

**Comment by DonOregano** [comment]
Maybe remove the vehicledb example app and related users guide info.
