### ISSUE TITLE
Multiple dispatches for WantsLastState subscriptions

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#224]
Controller::ProcessEntitySubscription currently ignores the problem with the last state being dispatched twice when getting postpones on an OnDeletedEntity and WantsLastState is set.

It must be analyzed if this is someting that has to be fixed.

Note that the WantsLastState is used only by dope.

Reported by: anderswiden

Original SourceForge Ticket `#225`: [safir/tickets/225](https://sourceforge.net/p/safir/tickets/225)

**Comment by DonOregano** [comment]
Dope handles double deletes properly, and this has not been an issue for anyone else. Reopen if needed.
