### ISSUE TITLE
Add description of the dope throttling mechanism.

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#226]
Add description of the dope throttling mechanism to Safir SDK Core User's Guide.

Reported by: anderswiden

Original SourceForge Ticket `#227`: [safir/tickets/227](https://sourceforge.net/p/safir/tickets/227)

**Comment by DonOregano** [comment]
Widde, you merged this functionality, can you write about it?

**Comment by anderswiden** [comment]
The Persistence Throttling mechanism is now described in User's Guide.
