### ISSUE TITLE
Implement Properties mapped into elements of dictionaries and sequences

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#228]
Properties are currently not possible to map to elements of dictionaries or sequences. Neither parameter or member mappings are implemented.

Reported by: DonOregano

Original SourceForge Ticket `#229`: [safir/tickets/229](https://sourceforge.net/p/safir/tickets/229)

**Comment by DonOregano** [comment]
Reopen if needed.
