### ISSUE TITLE
Check the level/guarantees given by Sourceforge regarding backups of Tickets/Wiki etc

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#23]
Check what level of backup is provided by Sourceforge regarding tickets, wiki etc.

The SVN repository on Sourceforge is just a mirror so that is no issue.

Reported by: anderswiden

Original SourceForge Ticket `#23`: [safir/tickets/23](https://sourceforge.net/p/safir/tickets/23)

**Comment by DonOregano** [comment]
Both github and sourceforge provide reasonable backups.
