### ISSUE TITLE
Dobmake buildlog behaves badly in Internet Explorer

### ISSUE THREAD

**Issue by DonOregano** [SafirSDK/safir-sdk-core#233]
The auto-reload feature of the build logs make Internet Explorer jump to the beginning of the log all the time. Pretty irritating!

**Comment by samme78** [comment]
Fixed by changing the javascript that reloads and scrolls the page. The page now stays at the same y-pos during a reload.

**Comment by DonOregano** [comment]
Backported to 6.0.x for 6.0.3
