### ISSUE TITLE
Entities get stuck in WaitingStates

### ISSUE THREAD

**Issue by anderswiden** [SafirSDK/safir-sdk-core#253]
When restarting a node in a multinode system the restarted node logs that entities get stuck in WaitingStates.

This may be related to issue #252

**Comment by DonOregano** [comment]
A log file:
[syslog.txt](https://github.com/SafirSDK/safir-sdk-core/files/10144/syslog.txt)

**Comment by DonOregano** [comment]
This issue might be solved by the fix made for #256.
