### ISSUE TITLE
Convert Sate to use Qt 

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#27]
Convert Sate to use Qt instead of dotnet. This will remove the last dependency to dotnet so that users, for example only interested in C++, don't need to bother with dotnet/mono at all. 

Reported by: anderswiden

Original SourceForge Ticket `#27`: [safir/tickets/27](https://sourceforge.net/p/safir/tickets/27)

**Comment by joelottosson** [comment]
Finally Sate has been completely rewritten in QT. The old Sate has been renamed to sate_legacy and will still exists for some time.
