### ISSUE TITLE
Client nodes should not be able to form systems without a Server node

### ISSUE THREAD

**Issue by DonOregano** [SafirSDK/safir-sdk-core#273]
Currently, without Light nodes (#270), two clients (that only have a server as seed) that start without a running server will form two separate systems. When a server starts it will connect to only one of these systems.
There should be a way to make it impossible for a client to form a system without a server present.

This is in a Client/Server system.

**Comment by DonOregano** [comment]
The proper solution to this problem is to introduce a feature to make SystemPicture and Control require that certain node types are present before forming a system.

At this stage we only want to require certain node types, but when more of the application start/stop functionality is added to Control we will probably want the requirements to be able to take more things into account.

The suggested solution is to make System Picture ask Control whether a set of nodes is enough to form a system or not, before a system is formed.

**Comment by anderswiden** [comment]
One approach to solve this problem would be to implement some basic Light Node functionality, in particular, the rules that prevents forming a system consisting of only light nodes. However, this "Light Node light" implementation is probably not less extensive and cheaper than the solution that requires certain node types. Besides, the "require certain node types" feature is useful in it its own right, even when the Light Nodes functionality is implemented.

**Comment by anderswiden** [comment]
Solved for 6.1
