### ISSUE TITLE
A registration state and associated deleted entity states got stuck in WaitingStates  

### ISSUE THREAD

**Issue by anderswiden** [SafirSDK/safir-sdk-core#276]
The following log shows that a registration state 'Registered' and associated entity states (explicitly deleted) are stuck in WaitingStates. In order to proceed with the investigation we need some more information about the event sequence that led to this situation.

<12>Oct 19 17:13:19 FM-SLB-125 dose_main[5480]: One or more items seem to be stuck in WaitingStates! If the system is artificially stopped when debugging or testing this warning can be ignored. ConnectionId=(-1, 1286700613240818919, 0) registrationState=RegistrationState               use_count: 1   Sender node: 1286700613240818919              Sender id: -1462335373571586589              Type: Capabilities.Devices.Raid.RequestedState                   HandlerId: SIM                              InstanceIdPolicy: HandlerDecidesInstanceId                           RegistrationStateKind: Registered                              RegistrationTime: 104030:1286700613240818919  entityStates= EntityState                         use_count: 1   Sender node: 1286700613240818919                              Sender id: -1   Type: Capabilities.Devices.Raid.RequestedState                              HandlerId: -6297501406829860570                   RegistrationTime: 104030:1286700613240818919                              InstanceId: 3219423896682445646                   CreationTime: 8:1286700613240818919         Version: 0                              EntityStateKind: Real                ExplicitlyDeleted: true             SourceIsPermanentStore: false                              HasBlob: false                              NumTimestamps: 1                   Timestamps: Top = 246121967352530  EntityState                              use_count: 1   Send...

**Comment by DonOregano** [comment]
This has not been seen again, so we're closing it. Reopen if it happens again!
