### ISSUE TITLE
Re-add removed dope redundancy

### ISSUE THREAD

**Issue by fumpa** [SafirSDK/safir-sdk-core#279]
Add the parameter Safir.Dob.PersistenceParameters.Standalone and the redundancy functionality for stand alone mode again.

**Comment by DonOregano** [comment]
Was removed as part of e5b295149b2879fac6e6351364a4925d3ed6cb2a

**Comment by DonOregano** [comment]
Is this mode *really* desirable?! It is error-prone and difficult to explain.

**Comment by DonOregano** [comment]
The StandaloneMode is now marked as deprecated in both the User's Guide and the parameters. Also a Warning will be issued to the system log if running dope in StandaloneMode.
