### ISSUE TITLE
TYPENAME column is needed

### ISSUE THREAD

**Issue by stfeky** [SafirSDK/safir-sdk-core#281]
Column TYPENAME was removed in dope in core 6
We are using this column and would like to have it reinserted into safir sdk core. 
and of course the column needs to be filled with the type name of the corresponding type id.

**Comment by DonOregano** [comment]
See also #264

**Comment by DonOregano** [comment]
Does this mean that the previous decision to leave the column blank is changed?

>> Förväntar ni er att det står något vettigt i den också? Eller kan den vara blank?

> Lämna den tom.
> Koden behöver inte fixas. Bara skriptet.

**Comment by stfeky** [comment]
Yes we have functionality that depends on this column and the information therein: 
"and of course the column needs to be filled with the type name of the corresponding type id."

**Comment by DonOregano** [comment]
Ok, just wanted to double check.
