### ISSUE TITLE
Add boost libraries to installer on windows

### ISSUE THREAD

**Issue by DonOregano** [SafirSDK/safir-sdk-core#342]
Customer wants Boost.Log and Boost.Serialization added to the install on Windows.

**Comment by DonOregano** [comment]
Is this still wanted?
Boost.Serialization looks like it is dying...

**Comment by fumpa** [comment]
Postpone this ticket for now.
We need Boost.Serialization compiled with zlib support.
Probably we needs more parts of Boost but we must investigate this first.

**Comment by DonOregano** [comment]
This will be irrelevant with 7.0, since we remove Boost stuff from our installer

**Comment by DonOregano** [comment]
As #370 has been merged into develop this is now obsolete.
