### ISSUE TITLE
Items stuck in waitingstates

### ISSUE THREAD

**Issue by MIWN** [SafirSDK/safir-sdk-core#344]
During start/stop tests dose_main terminates with logs that tell that items are stuck in WaitingStates.
Setup:
3 Nodes (128, 129 and 130)
Node 130 is running server system in SAFIR_INSTANCE=1 and client system on SAFIR_INSTANCE=2.
Client system are running on node 128, 129.
Clients are started and stopped on 128, 129 and 130(instance 2), server on 130 is running all the time.
After a while dose_main is terminated on all 3 clients with the attached log.
[dose.txt](https://github.com/SafirSDK/safir-sdk-core/files/850083/dose.txt)

Server is still running and it is possible to restart the clients after the crash.

**Comment by DonOregano** [comment]
Is this something that you can repeat?

This is probably the same thing as #276

**Comment by DonOregano** [comment]
This turned out to be an issue with pool distribution at startup. The queue size counter in Communication got out of sync when nodes were starting and stopping frequently, causing pool distribution to hang indefinitely. This in turn meant that the regular states that were being sent would get stuck in waiting states.

**Comment by DonOregano** [comment]
Fixed in 1ba43d490908538d8e3d9a6afc7bd423797c2c5d

**Comment by DonOregano** [comment]
This appears to be three separate issues. Two of which appear to be solved now.

**Comment by DonOregano** [comment]
Well, the third issue appears to have been a false alarm. So, we're closing this issue now.

The second issue turned out to be another problem in Communication, where, if dose_main started sending SingleReceiver messages immediately after injecting a node, it would discard the message.
