### ISSUE TITLE
Mirror NodeInfo in global entities

### ISSUE THREAD

**Issue by joelottosson** [SafirSDK/safir-sdk-core#471]
Let the Status application mirror the limited scoped NodeInfo entities in global objects that can be seen by other lightnodes.

**Comment by DonOregano** [comment]
Does this mean that the Status application should be allowed to update entities even we're in low memory? Like dose_main does with the NodeInfo entities.

**Comment by DonOregano** [comment]
Implemented in d873ed836b6f191aa81e1cc3a72edf4b54c7bf77
