### ISSUE TITLE
Zombie-handling for RequestInQueues

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#48]
RequestInQueue needs to be emptied of responses before the queue is removed in the case of sending one response and then unregistering the handler. 

dose_main would like to do this.

Reported by: DonOregano

Original SourceForge Ticket `#49`: [safir/tickets/49](https://sourceforge.net/p/safir/tickets/49)

**Comment by DonOregano** [comment]
This seems to be a rather strange way of implementing a handler. If someone wants this we can discuss it and reopen the issue.
