### ISSUE TITLE
Generated c++ code does not compile when there are circular dependencies between dou classes

### ISSUE THREAD

**Issue by joelottosson** [SafirSDK/safir-sdk-core#480]
Dou-files with circular dependencies are valid according to dots, but the generated c++ code doesn't compile.
Either the generated code should be fixed or dots should report circular dependencies as an error.

**Comment by DonOregano** [comment]
This could be solved by adding a forward declaration for each used type in the generated header files. For example if Test.Example.MemberTypes.dou uses Another.Test.MemberArrays.dou the MemberTypes.h needs the following forward declarations:

`
namespace Another
{
  namespace Test
  {
    class MemberArrays;
    typedef std::shared_ptr<MemberArrays> MemberArraysPtr;
    typedef std::shared_ptr<const MemberArrays> MemberArraysConstPtr;

    typedef Safir::Dob::Typesystem::ObjectContainerImpl<MemberArrays> MemberArraysContainer;
    typedef Safir::Dob::Typesystem::ArrayContainer<MemberArraysContainer> MemberArraysContainerArray;
    typedef Safir::Dob::Typesystem::GenericObjectSequenceContainer<MemberArrays> MemberArraysSequenceContainer;
  }
}`

The forward declarations themselves are not difficult to generate, but what is difficult is the nested namespaces. The way the dod files and dots_v are written there is currently (probably) no way to do this. So in all likelyhood we need to add more features to dots_v, which is not a particularly easy task.

I would estimate around 80 hours of work for this, which to me seems unreasonable for this feature.
I will close this issue for now, and we can reopen it if we decide this is something that we want to do.

**Comment by DonOregano** [comment]
@fumpa, we can discuss this if you want more details.
