### ISSUE TITLE
Provide a script that collects SDK Core crash dump data

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#49]
Provide a script that makes it easy to collect all necessary crash dump data, related to SDK Core, from a "tower" installation.
Today the normal installation structure is that SDK Core and the application specific binaries all are located under runtime/bin. Zipping this directory means that project specific information (e.g pdb-files on Windows) could get included in the zip which might be inappropriate in some situations.

Reported by: anderswiden

Original SourceForge Ticket `#50`: [safir/tickets/50](https://sourceforge.net/p/safir/tickets/50)

**Comment by DonOregano** [comment]
Not really needed any longer, since users are expected to use our installation packages. They only need to send the dmp file and tell us which package they are using and that should be enough. There is info on this in the user's guide.
