### ISSUE TITLE
Better dictionary parameter reflection

### ISSUE THREAD

**Issue by joelottosson** [SafirSDK/safir-sdk-core#491]
It is impossible to retrieve all valid keys and hence all key-value pairs from from a dictionary parameter. With some effort it is possible to loop through all values, but you will not get the corresponding key.
There must be a way in the parameters reflection API to get all keys or key-value pairs. Maybe there should also be an easy-to-use helper in the generated code for iteration over all key-values in a dictionary parameter.

**Comment by DonOregano** [comment]
Do I understand it correctly that we need functions in Safir::Dob::Typesystem::Parameters to do the following:
 * Get number of keys in a specific dictionary parameter
 * Get key type for a dictionary parameter
 * Get the key value for each specific key index in a dictionary parameter (one function per type of key)

For the generated code we could add utility functions that allow fetching of number of keys and fetching parameter by key index, for each parameter dictionary.
