### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by FenixH** [SafirSDK/safir-sdk-core#503]
Hello,

I am trying to build from source on a Windows 10 x64 machine, and have followed the instructions in https://github.com/SafirSDK/safir-sdk-core/blob/master/BUILD.Windows.txt. I used chocolatey to install all packages. I get the following error when i call build.py (it is given after several hours have passed): 

```
build\build.py --package --use-studio vs2022
__msvc14_find_vc2017() result: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build
Loading Visual Studio Environment
Running '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.3 & set' to extract environment
Setting environment variable 'VisualStudioVersion' to '17', to encourage conan packages to build correctly.
Setting environment variable 'CONAN_CMAKE_GENERATOR' to 'Ninja', to encourage conan packages to build correctly.
 - in config Debug
   + testing
   + installing to staging area
 - in config RelWithDebInfo
   + testing
   + installing to staging area
Building installation package
Traceback (most recent call last):
  File "C:\Projects\safir-sdk-core\build\build.py", line 995, in <module>
    (tests, failed) = main()
  File "C:\Projects\safir-sdk-core\build\build.py", line 976, in main
    builder.build()
  File "C:\Projects\safir-sdk-core\build\build.py", line 495, in build
    self.__package()
  File "C:\Projects\safir-sdk-core\build\build.py", line 499, in __package
    self.stage_package()
  File "C:\Projects\safir-sdk-core\build\build.py", line 806, in stage_package
    self._run_command(command, "Packaging ")
  File "C:\Projects\safir-sdk-core\build\build.py", line 564, in _run_command
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, env=env)
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by joelottosson** [comment]
Hi,
The build.py script is primarily used to build installers. If you need an installer you find builds for all platforms under releases.
If you want to build the code yourself then install all the prerequisites stated in BUILD.Windows.txt and then open the safir_sdk_core folder in VS2022. It will automatically configure cmake, then it should be possible to build. Alternatively build from command line. First configure cmake:
cmake . -DCMAKE_BUILD_TYPE=Debug -G Ninja
then build by running comman
ninja

**Comment by DonOregano** [comment]
Yes, what the build script does is load a correct environment and build the system and then create installation packages. It looks like what it is the script can't find is NSIS, i.e. the Windows packager tool that we use. If you installed that with chocolatey you may need to add it to your PATH, maybe.
That is if you are actually trying to build the installer packages :-D

**Comment by FenixH** [comment]
Sorry about my late reply. 

I am trying to get the examples to compile+debug through VS2022. I installed the requirements (choco+pip packages) described in BUILD.Windows.txt, but I am getting an error when I open the safir_sdk_core folder through VS2022:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at out/build/x64-Debug/conan.cmake:61 (message):
  Conan: Unknown MSVC compiler version [1940]		C:\Projects\safir-sdk-core\out/build/x64-Debug/conan.cmake	61		
``

**Comment by DonOregano** [comment]
I thiiiink you may have been bitten by the fact that MS changed version numbers in unexpected ways for their latest updates to vs2022. I only recently updated to 17.10.x recently, and then everything stopped building.
So, I have now updated our build system to use conan 2 and  it now works with the latest vs2022 versions.
So give it another try, please.

**Comment by DonOregano** [comment]
Oh, this is only in the develop branch so far.

**Comment by DonOregano** [comment]
Closing this for now. Reopen if you still can't get it going!
