### ISSUE TITLE
Context chapter in Users guide should probably not use APP/PRS acronyms

### ISSUE THREAD

**Issue by SafirSDKImport** [SafirSDK/safir-sdk-core#94]
The Context chapter in the SUG uses APP and PRS to describe different types of applications. This should probably be changed to something more generic and understandable for people outside Saab...

Reported by: DonOregano

Original SourceForge Ticket `#95`: [safir/tickets/95](https://sourceforge.net/p/safir/tickets/95)

**Comment by DonOregano** [comment]
Changed it to use APP and GUI.
